version: "3"
services:
  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: ./Dockerfile.prod
    restart: unless-stopped
    env_file: .env.production
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      AWS_REGION: eu-west-1
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      BUCKET_STRAPI: com.aelitneg.strapi
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - .env.production:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
