version: "3"
services:
  frontend:
    container_name:  frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/.env.local:/app/.env.local
      - ./frontend/.next:/app/.next
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - '3000:3000'
    networks:
      - strapi
  strapi:
    build:
      context: ./strapi
      dockerfile: ./Dockerfile.dev
    env_file: .env.development
    environment: 
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AWS_S3_ENDPOINT: http://minio:9000
      BUCKET_STRAPI: strapi
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - .env.development:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env.development
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/mysql # if you want to use a bind folder
    ports:
      - "3306:3306"
    networks:
      - strapi
  minio: 
    container_name: minio
    restart: unless-stopped
    image: minio/minio:latest
    command: minio server --console-address ":9001"
    env_file: .env.development
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      MINIO_VOLUMES: /mnt/minio-data
    volumes:
      - minio-data:/mnt/minio-data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - strapi
  mc:
    container_name: mc
    image: minio/mc:latest
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    entrypoint: /docker-entrypoint.sh
    volumes: 
      - ./mc/docker-entrypoint.sh:/docker-entrypoint.sh
    networks:
      - strapi
    depends_on:
      - minio

volumes:
  strapi-data:
  minio-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
